version: "2"
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./logs:/var/log/nginx
      - ../:/var/www/html
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - fpm

  fpm:
    image: koshpaevsv/php7.1
    container_name: fpm
    user: 1000:1000
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    expose:
      - 9000
    links:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    volumes:
      - ./postgres/var/lib/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lara
      - POSTGRES_PASSWORD=lara
      - POSTGRES_DB=lara
    ports:
      - "5432:5432"
